# Generated by Django 5.0.2 on 2024-09-08 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_author_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='LentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.book')),
            ],
        ),
    ]
